services:
  backend:
    image: techstore_backend
    container_name: backend
    build:
      context: ./backend
      dockerfile: docker/dev/Dockerfile
    entrypoint: sh ./entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000
    env_file: ./backend/.env.development
    volumes:
      - ./backend:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:16-alpine
    volumes:
      - db16_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=techstore
      - POSTGRES_PASSWORD=techstore
      - POSTGRES_DB=techstore
volumes:
  db16_data: